[package]
name = "installed_programs_finder"
version = "0.1.0"
authors = ["monsterzack5"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
